source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JSONJam_Example' do
  pod "JSONJam", :path => "../"
  pod "JSONHelper", :git => 'https://github.com/Pluto-tv/JSONHelper.git'
end

target 'JSONJam_Tests' do
  pod "JSONJam", :path => "../"
  pod "JSONHelper", :git => 'https://github.com/Pluto-tv/JSONHelper.git'
end
